apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rails
  name: rails
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          image: seemiller/demo:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: rails-env
          env:
            - name: DATABASE_URL
              value: mysql2://root:password@mysql-service.demo.svc.cluster.local/demo_production
#            - name: DATABASE_URL
#              valueFrom:
#                secretKeyRef:
#                  name: rails-secrets
#                  key: database-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: secret-key-base
