apiVersion: v1
kind: Secret
metadata:
  name: rails-secrets
  namespace: demo
type: Opaque
data:
  database-url: bXlzcWwyOi8vZGVtbzpkZW1vLXBhc3N3b3JkQG15c3FsLXNlcnZpY2UuZGVtby5zdmMuY2x1c3Rlci5sb2NhbC9kZW1vX3Byb2R1Y3Rpb24=
  secret-key-base: ZWQ3MGE4YjZmODc5ZmIxNzJkMDQ4NzQwMTBkZTFhYTM4ZjhlMTkwNWIzY2JhNmUzNmNhYWE5NTk0ZDMyZGQ4MmQ1ZjRiYWJmMmVlZTg5MDUwOTVjZjdlNDQ5MTQ1NzhjOWM5YjIxYjgzYjFiNjZhMTk4NDY5MWRjMWExYWM3NTAK
